VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IExtractFrmForceMethod"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "Operation.ExtractFrameForce"
'@Interface

Option Explicit

Public Function ExtractForce() As Collection
End Function

Public Sub Initialize(model As StrModel, UFControl As Object)
End Sub
