VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IMapConnMethod"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "Operation.ConnAnalysis"
'@Interface

Option Explicit

'Private mJts As Collection
'Private mConnType As StrConnection

Public Function MapConnection(connType As StrConnectionType) As Integer
End Function

Public Sub Initialize(model As StrModel)
End Sub

'Public Property Get jts() As Collection
'End Property
'
'Public Property Let jts(Value As Collection)
'End Property
'
'Public Property Get connType() As StrConnection
'End Property
'
'Public Property Let connType(Value As StrConnection)
'End Property

