VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IView"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("MVVM.Infrastructure")
Option Explicit
Property Get CloseState() As Integer

End Property
Property Get ViewModel() As Object

End Property

Public Sub Show()
End Sub

'Public Sub Hide()
'End Sub
Public Sub Initialize(vm As Object)
End Sub
