VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "TagSelectorFrameData"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("DataSheet.ModelData")

Option Explicit

Public Property Get eleID() As String
    eleID = "eleID"
End Property

Public Property Get section() As String
    section = "section"
End Property

Public Property Get jtI() As String
    jtI = "jtI"
End Property

Public Property Get jtJ() As String
    jtJ = "jtJ"
End Property

Public Property Get eleLen() As String
    eleLen = "eleLen"
End Property

Public Property Get memID() As String
    memID = "memID"
End Property

Public Property Get eleLocalAxis() As String
    eleLocalAxis = "eleLocalAxis"
End Property

Public Property Get EleType() As String
    EleType = "eleType"
End Property
Public Property Get EleOrientationType() As String
    EleOrientationType = "eleOrientationType"
End Property


